### PR TITLE
Spanish Translation (App & Readme)

### PR DESCRIPTION
**Pull request by another-sapiens**
I just saw Docus a while ago looking for new apps on F-Droid and I'm loving it. Great work!
Definitely worthy of a translation, so here you go.

### CODE REVIEW

**Comment by Breta01** [comment]
Thank you very much!
I will create a new release with translation within next few days.

**Comment by Breta01** [comment]
The new release is out! It is in process of publishing on Google Play. Thank you once again.

I actually find out that I missed some hard-coded strings in code. I updated the strings.xml, so that future translations should cover everything.

**Comment by another-sapiens** [comment]
Nice! I just made a new pull request with the updated translation.

**Comment by another-sapiens** [comment]
Also thank you for translating the ambiguous lines, you've saved me a few minutes of checking the in-app context!

**Pull request merged**
