### PR TITLE
ID localization

### PR DESCRIPTION
**Pull request by the7thNightmare**
This is the translation of Docus in Indonesian Language. Thank you.

### CODE REVIEW

**Comment by Breta01** [comment]
Looks good. Thank you very much! I will try to release new version of the application during the week.

**Comment by Breta01** [comment]
Hi @the7thNightmare once again thank you for the localization. I am sorry for a delay with the release. I just upload it to google play, so it should be up within next few hours.

**Comment by the7thNightmare** [comment]
Thanks for the release, but one question, how do I change the language? There's no button to do that in the app, and it didn't automatically change the language to Indonesian language, it is still English in the app. Thanks.

**Comment by Breta01** [comment]
Normally you should see the language change automatically just by changing the system language.
I looked into the issue and it seems that some older Android versions uses `values-in` instead of `values-id` as Indonesian language code. My phone doesn't recognize `id` as well. So I will try adding the `values-in` and see if it helps.
I will let you know how it goes then.

**Comment by Breta01** [comment]
@the7thNightmare I sent the release to google play. Once it is up, just change your system language to Indonesian and it should automatically work.

**Comment by the7thNightmare** [comment]
Yes, now it works correctly. Thanks.

**Pull request merged**
